spring.application.name : worker-service
server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: worker-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

problem-service:
  url: http://localhost:8082

topics:
  submission: submission-topic
  execution-result: execution-result-topic