spring.application.name : worker-service
server:
  port: 8084

spring:
  kafka:
    consumer:
      group-id: worker-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.MS_code_execution_platform.worker_service.dto.SubmissionEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

problem-service:
  url: http://localhost:8082

topics:
  submission: submission-topic
  execution-result: execution-result-topic