server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8086/.well-known/jwks.json
          issuer-uri: https://auth-service
          audiences: ms-code-execution

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**

            - id: problem-service
              uri: lb://PROBLEM-SERVICE
              predicates:
                - Path=/problems/**

            - id: submission-service
              uri: lb://SUBMISSION-SERVICE
              predicates:
                - Path=/submissions/**

            - id: execution-result-service
              uri: lb://EXECUTION-RESULT-SERVICE
              predicates:
                - Path=/api/results/**

            - id: solution-service
              uri: lb://SOLUTION-SERVICE
              predicates:
                - Path=/solutions/**






eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/