-- Matches com.MS_code_execution_platform.submission_service.entity.Submission.
-- output/reason use TEXT rather than the implicit varchar(255) default -
-- execution output and error detail can easily exceed 255 chars, consistent
-- with "code" on the same entity already being explicitly TEXT.
CREATE TABLE submission (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      uuid,
    problem_id   bigint,
    code         TEXT,
    language     varchar(255),
    status       varchar(255),
    output       TEXT,
    reason       TEXT,
    submitted_at timestamp
);
