-- Matches com.MS_code_execution_platform.solution_service.entity.Solution / SolutionPart.
-- One row per problem (problem_id references problem-service's Problem.id,
-- no cross-service FK - same relationship submission.problem_id already has),
-- with its parts broken into separate rows so each can be fetched/edited
-- independently (see SolutionPart's Javadoc).
CREATE TABLE solution (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id            bigint NOT NULL UNIQUE,
    visualizer_object_key varchar(255)
);

CREATE TABLE solution_part (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solution_id bigint NOT NULL REFERENCES solution(id) ON DELETE CASCADE,
    ordinal     integer NOT NULL,
    title       varchar(255) NOT NULL,
    markdown    TEXT NOT NULL,
    UNIQUE (solution_id, ordinal)
);
