-- Matches com.MS_code_execution_platform.solution_service.entity.SolutionNote.
-- Per-user free-text notes for a problem - not tied to a `solution` row (a
-- user can jot notes on a problem before an admin has written a solution at
-- all), so problem_id is a plain reference here too, same as on `solution`.
CREATE TABLE solution_note (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id bigint NOT NULL,
    user_id    uuid NOT NULL,
    content    TEXT NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (problem_id, user_id)
);
