-- Matches com.MS_code_execution_platform.problem_service.entity.Problem and
-- .TestCase exactly (Hibernate's default snake_case naming; table names are
-- the unannotated entity class names lowercased - "problem", "test_case").
CREATE TABLE problem (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255),
    description     TEXT,
    constraints     TEXT,
    time_limit_ms   integer,
    memory_limit_mb integer
);

CREATE TABLE test_case (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input           TEXT,
    expected_output TEXT,
    hidden          boolean NOT NULL,
    input_s3_key    varchar(255),
    expected_s3_key varchar(255),
    ordinal         integer,
    is_sample       boolean NOT NULL,
    weight          integer,
    problem_id      bigint REFERENCES problem(id)
);
