-- Per-user edges between two problems, for the Practice page's 3D graph
-- view (an Obsidian-style personal map, not a shared prerequisite graph -
-- each user only ever sees/edits their own rows). Canonicalized so
-- problem_a_id < problem_b_id always, letting the unique constraint catch
-- both directions of the same pair.
CREATE TABLE problem_connection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    problem_a_id bigint NOT NULL REFERENCES problem(id) ON DELETE CASCADE,
    problem_b_id bigint NOT NULL REFERENCES problem(id) ON DELETE CASCADE,
    created_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT uq_connection UNIQUE (user_id, problem_a_id, problem_b_id)
);
