-- Free-standing "topic card" nodes the user can place on the Practice
-- page's 3D graph to organize problems into a personal mind-map (e.g. a
-- "Strings" card connected to pattern cards, each connected to the actual
-- problems that use that pattern) - per-user, same ownership model as
-- graph_connection below.
CREATE TABLE graph_card (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    title varchar(120) NOT NULL,
    created_at timestamp NOT NULL DEFAULT now()
);

-- Generalizing problem_connection's edges to connect ANY two graph nodes (a
-- problem or a card, in either combination) now that cards exist, rather
-- than only two problems. node_a_type/node_b_type discriminate which table
-- node_a_id/node_b_id point into - deliberately not a real FK (a single id
-- column can't reference two different tables), so existence/ownership of
-- the referenced node is instead enforced in ConnectionService at
-- create-time. Renamed problem_connection -> graph_connection to match:
-- it's no longer problem-specific. Existing rows are preserved and
-- backfilled to node_a_type/node_b_type = 'PROBLEM'.
ALTER TABLE problem_connection RENAME TO graph_connection;
ALTER TABLE graph_connection RENAME COLUMN problem_a_id TO node_a_id;
ALTER TABLE graph_connection RENAME COLUMN problem_b_id TO node_b_id;
ALTER TABLE graph_connection DROP CONSTRAINT problem_connection_problem_a_id_fkey;
ALTER TABLE graph_connection DROP CONSTRAINT problem_connection_problem_b_id_fkey;
ALTER TABLE graph_connection ADD COLUMN node_a_type varchar(10) NOT NULL DEFAULT 'PROBLEM';
ALTER TABLE graph_connection ADD COLUMN node_b_type varchar(10) NOT NULL DEFAULT 'PROBLEM';
ALTER TABLE graph_connection ALTER COLUMN node_a_type DROP DEFAULT;
ALTER TABLE graph_connection ALTER COLUMN node_b_type DROP DEFAULT;
ALTER TABLE graph_connection DROP CONSTRAINT uq_connection;
ALTER TABLE graph_connection ADD CONSTRAINT uq_graph_connection
    UNIQUE (user_id, node_a_type, node_a_id, node_b_type, node_b_id);
