-- Where a user has manually dragged one graph node (a problem or a
-- GraphCard) to on the Practice page's 3D graph view - lets a hand-arranged
-- layout survive a page reload instead of the physics simulation
-- re-scattering everything. Personal, same ownership model as
-- graph_connection/graph_card. Upserted (see GraphPositionService), so at
-- most one row per (user, node) - a node the user never dragged just has no
-- row here and falls back to wherever the client's own simulation places it.
CREATE TABLE graph_node_position (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    node_type varchar(10) NOT NULL,
    node_id bigint NOT NULL,
    x double precision NOT NULL,
    y double precision NOT NULL,
    z double precision NOT NULL,
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT uq_graph_node_position UNIQUE (user_id, node_type, node_id)
);
