-- Backs the Practice page's new "Board" view: a 2D, whimsical-style
-- freeform canvas, independent of the existing graph_card/graph_connection/
-- graph_node_position tables (the 3D graph view keeps its own data - see
-- V6/V7). Same per-user ownership shape as those tables, just 2D (x/y, no
-- z) and under separate table names so the two views never share nodes.

CREATE TABLE board_card (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    title varchar(120) NOT NULL,
    color varchar(16),
    created_at timestamp NOT NULL DEFAULT now()
);

-- node_a_type/node_b_type discriminate whether node_a_id/node_b_id points
-- into board_card or problem - not a real FK for the same reason
-- graph_connection isn't (a single id column can't reference two different
-- tables); existence/ownership is enforced in BoardNodeValidator instead.
CREATE TABLE board_connection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    node_a_type varchar(10) NOT NULL,
    node_a_id bigint NOT NULL,
    node_b_type varchar(10) NOT NULL,
    node_b_id bigint NOT NULL,
    color varchar(16),
    created_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT uq_board_connection UNIQUE (user_id, node_a_type, node_a_id, node_b_type, node_b_id)
);

-- Upserted (one row per user+node) - a node the user never dragged just has
-- no row here and starts at a default spawn position on the client.
CREATE TABLE board_node_position (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    node_type varchar(10) NOT NULL,
    node_id bigint NOT NULL,
    x double precision NOT NULL,
    y double precision NOT NULL,
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT uq_board_node_position UNIQUE (user_id, node_type, node_id)
);
